In [1]:
from sklearn.datasets import load_boston
boston = load_boston()

In [2]:
print(type(boston))
print(boston.keys())

<class 'sklearn.utils.Bunch'>
dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])


In [3]:
print(boston.data.shape)
print(boston.target.shape)
print(boston.feature_names)

(506, 13)
(506,)
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


_NOTE:_ 13 features & 506 Rows of data

In [4]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [5]:
import numpy as np
import pandas as pd

boston_df = pd.DataFrame(boston.data)
print(boston_df.head())

        0     1     2    3      4      5     6       7    8      9     10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12  
0  396.90  4.98  
1  396.90  9.14  
2  392.83  4.03  
3  394.63  2.94  
4  396.90  5.33  


In [6]:
X = np.array(boston_df, dtype=float)
y = np.array(boston.target, dtype=float)

print(X[:5])
print(y[:5])

[[6.3200e-03 1.8000e+01 2.3100e+00 0.0000e+00 5.3800e-01 6.5750e+00
  6.5200e+01 4.0900e+00 1.0000e+00 2.9600e+02 1.5300e+01 3.9690e+02
  4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 6.4210e+00
  7.8900e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9690e+02
  9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 7.1850e+00
  6.1100e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9283e+02
  4.0300e+00]
 [3.2370e-02 0.0000e+00 2.1800e+00 0.0000e+00 4.5800e-01 6.9980e+00
  4.5800e+01 6.0622e+00 3.0000e+00 2.2200e+02 1.8700e+01 3.9463e+02
  2.9400e+00]
 [6.9050e-02 0.0000e+00 2.1800e+00 0.0000e+00 4.5800e-01 7.1470e+00
  5.4200e+01 6.0622e+00 3.0000e+00 2.2200e+02 1.8700e+01 3.9690e+02
  5.3300e+00]]
[24.  21.6 34.7 33.4 36.2]


In [7]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader

In [8]:
class NN(nn.Module):
    def __init__(self, num_features):
        super(NN, self).__init__()
        self.num_features = num_features
        self.layer1 = nn.Linear(num_features, 16)
        self.layer2 = nn.Linear(16, 8)
        self.ouput_layer = nn.Linear(8, 1)
        
    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.ouput_layer(x)
        return x

In [9]:
# Hyper-paramaters
num_epochs = 40
batch_size = 64
learning_rate = 0.001
num_features = 13

In [10]:
y = y.reshape(y.shape[0], -1)
print(X.shape)
print(y.shape)
dataset = np.concatenate([X, y] , axis=1)

(506, 13)
(506, 1)


In [11]:
dataset = dataset.astype(np.float32)
dataset_tensor = torch.from_numpy(dataset)
print(dataset_tensor.shape)

torch.Size([506, 14])


In [12]:
from torch.utils.data import random_split
training_data, testing_data = random_split(dataset_tensor, [400, 106])
print(training_data[0])
print(type(training_data[0]))
print(testing_data[0])
print(type(testing_data[0]))

tensor([5.5150e-02, 3.3000e+01, 2.1800e+00, 0.0000e+00, 4.7200e-01, 7.2360e+00,
        4.1100e+01, 4.0220e+00, 7.0000e+00, 2.2200e+02, 1.8400e+01, 3.9368e+02,
        6.9300e+00, 3.6100e+01])
<class 'torch.Tensor'>
tensor([3.6150e-02, 8.0000e+01, 4.9500e+00, 0.0000e+00, 4.1100e-01, 6.6300e+00,
        2.3400e+01, 5.1167e+00, 4.0000e+00, 2.4500e+02, 1.9200e+01, 3.9690e+02,
        4.7000e+00, 2.7900e+01])
<class 'torch.Tensor'>


In [13]:
train_loader = DataLoader(dataset=training_data, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(dataset=testing_data, batch_size=batch_size, shuffle=True)

In [14]:
model = NN(num_features=num_features)
loss_function = nn.MSELoss(reduction='mean')
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [17]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.train()

for epoch in range(num_epochs):        
    for batch_idx, batch_data in enumerate(train_loader):
        data, targets = (torch.split(batch_data, [13,1], dim=1))

        data = data.to(device=device)
        targets = targets.to(device=device)
        
        predicted_output = model(data)
        loss = loss_function(predicted_output, targets)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
    print(f'Epoch {epoch+1} completed with Loss {loss}')
    print()
print()
print("Training Completed!")
# Saving Trained Model
checkpoint = {'state_dict': model.state_dict(), 'optimizer': optimizer.state_dict()}
torch.save(checkpoint, 'Trained Models/Boston_House_Pricing.pth.tar')
print("Model Saved Successfully!")

Epoch 1 completed with Loss 96.17192077636719

Epoch 2 completed with Loss 51.09019088745117

Epoch 3 completed with Loss 53.63617706298828

Epoch 4 completed with Loss 32.03709411621094

Epoch 5 completed with Loss 25.5443058013916

Epoch 6 completed with Loss 47.82583999633789

Epoch 7 completed with Loss 28.345806121826172

Epoch 8 completed with Loss 37.25379943847656

Epoch 9 completed with Loss 73.01223754882812

Epoch 10 completed with Loss 37.38441467285156

Epoch 11 completed with Loss 40.180885314941406

Epoch 12 completed with Loss 63.965232849121094

Epoch 13 completed with Loss 38.20222473144531

Epoch 14 completed with Loss 123.7923355102539

Epoch 15 completed with Loss 40.38772201538086

Epoch 16 completed with Loss 31.257686614990234

Epoch 17 completed with Loss 36.5189208984375

Epoch 18 completed with Loss 78.42407989501953

Epoch 19 completed with Loss 109.02842712402344

Epoch 20 completed with Loss 92.76913452148438

Epoch 21 completed with Loss 57.02490234375

E

In [18]:
# Checking Validation Set
model.eval()
for batch_idx, batch_data in enumerate(test_loader):
    data, targets = (torch.split(batch_data, [13,1], dim=1))

    data = data.to(device=device)
    targets = targets.to(device=device)

    predicted_output = model(data)
    loss = loss_function(predicted_output, targets)

print(f'Validation completed with Loss {loss}')

Validation completed with Loss 50.16023254394531


In [19]:
# Getting outputs from the model
import random
rand_int = random.randint(0,506)
data = boston.data[rand_int]
target = boston.target[rand_int]
print(data, target)

[  0.85204   0.        8.14      0.        0.538     5.965    89.2
   4.0123    4.      307.       21.      392.53     13.83   ] 19.6


In [20]:
data = np.array(data, dtype=float)
data = data.astype(np.float32)
data_tensor = torch.from_numpy(data)
data_tensor = data_tensor.to(device=device)
predicted_output = model(data_tensor)

In [21]:
print(f'Actual Value: {target}')
print(f'Predicted Value: {predicted_output[0]}')

Actual Value: 19.6
Predicted Value: 22.980344772338867


In [24]:
# Loading Checkpoint
saved_model = torch.load('Trained Models/Boston_House_Pricing.pth.tar')
model.load_state_dict(saved_model['state_dict'])
optimizer.load_state_dict(saved_model['optimizer'])

In [25]:
rand_int = random.randint(0,506)
data = boston.data[rand_int]
target = boston.target[rand_int]
data = np.array(data, dtype=float)
data = data.astype(np.float32)
data_tensor = torch.from_numpy(data)
data_tensor = data_tensor.to(device=device)
predicted_output = model(data_tensor)
print(f'Actual Value: {target}')
print(f'Predicted Value: {predicted_output[0]}')

Actual Value: 14.1
Predicted Value: 7.417234420776367
